### ISSUE TITLE
RSA_SIGN_PSS_4096_SHA512 uses incorrect Hash

### ISSUE THREAD

**Issue by josephlr** [sethvargo/go-gcpkms#4]
You can see the issue here: https://github.com/sethvargo/go-gcpkms/blob/d27de45772d4964f90de6bc3aa86b06056ae74d0/pkg/gcpkms/signer.go#L114
That hash algorithm should use SHA512.

This isn't super critical as `RSA_SIGN_PSS_4096_SHA512` is a very rarely used algorithm.

**Comment by sethvargo** [comment]
Fixed thanks!
